#ScenicView properties
#Sat Apr 04 00:36:17 CEST 2026
autoRefreshStyleSheets=false
automaticScenegraphStructureRefreshing=true
collapseContainerControls=false
collapseControls=true
ignoreMouseTransparentNodes=true
registerShortcuts=true
showBaseline=false
showBounds=true
showCSSProperties=false
showDefaultProperties=true
showFilteredNodesInTree=true
showInvisibleNodes=false
showNodesIdInTree=false
showSearchBar=true
splitPaneDividerPosition=0.4986440677966102
stageHeight=527.0
stageWidth=1475.0
